name: RSSNotify

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes (modify as needed)
  workflow_dispatch:         # manual trigger

permissions:
  contents: write            # allow pushing updates

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install feedparser sendgrid

      - name: Execute RSS notifier
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python rss_notifier.py

      - name: Upload state file
        uses: actions/upload-artifact@v4
        with:
          name: seen-posts
          path: seen_posts.txt

      - name: Commit updated seen_posts.txt
        run: |
          git diff --quiet seen_posts.txt || (
            git config user.name "github-actions[bot]" &&
            git config user.email "github-actions[bot]@users.noreply.github.com" &&
            git add seen_posts.txt &&
            git commit -m "Update seen_posts.txt" &&
            git push
          )
